
; Make hjkl sensible on colemak
(defun to-colemak ()
  (interactive)
;  (define-key evil-normal-state-map "l" 'evil-search-next)
  (define-key evil-normal-state-map "l" 'evil-insert)
  (define-key evil-normal-state-map "j" 'evil-forward-word-end)
;  (define-key evil-normal-state-map "k" 'evil-insert)
  (define-key evil-normal-state-map "k" 'evil-search-next)
  (define-key evil-normal-state-map "n" 'evil-next-line)
  (define-key evil-normal-state-map "e" 'evil-previous-line)
  (define-key evil-normal-state-map "i" 'evil-forward-char)
;  (define-key evil-visual-state-map "l" 'evil-search-next)
  (define-key evil-visual-state-map "l" 'evil-insert)
  (define-key evil-visual-state-map "j" 'evil-forward-word-end)
;  (define-key evil-visual-state-map "k" 'evil-insert)
  (define-key evil-visual-state-map "k" 'evil-search-next)
  (define-key evil-visual-state-map "n" 'evil-next-line)
  (define-key evil-visual-state-map "e" 'evil-previous-line)
  (define-key evil-visual-state-map "i" 'evil-forward-char))
(defun to-qwerty ()
  (interactive)
  (define-key evil-normal-state-map "n" 'evil-search-next)
  (define-key evil-normal-state-map "e" 'evil-forward-word-end)
  (define-key evil-normal-state-map "i" 'evil-insert)
  (define-key evil-normal-state-map "j" 'evil-next-line)
  (define-key evil-normal-state-map "k" 'evil-previous-line)
  (define-key evil-normal-state-map "l" 'evil-forward-char)
  (define-key evil-visual-state-map "n" 'evil-search-next)
  (define-key evil-visual-state-map "e" 'evil-forward-word-end)
  (define-key evil-visual-state-map "i" 'evil-insert)
  (define-key evil-visual-state-map "j" 'evil-next-line)
  (define-key evil-visual-state-map "k" 'evil-previous-line)
  (define-key evil-visual-state-map "l" 'evil-forward-char))
